# THIS FILE WAS AUTOMATICALLY GENERATED. DO NOT EDIT.

DEFINES += -DNDEBUG=1 -DTRIMMED=1
CSRCS += kiss_fft.c
CSRCS += kiss_fftr.c
RTL_FLAGS += -MD
VISIBILITY_FLAGS := 
LIBRARY_NAME := media_kiss_fft
FORCE_STATIC_LIB := 1
REAL_LIBRARY := media_kiss_fft.lib
DEFINES += -DMOZ_HAS_MOZGLUE -DMOZILLA_INTERNAL_API -DIMPL_LIBXUL
