# THIS FILE WAS AUTOMATICALLY GENERATED. DO NOT EDIT.

DEFINES += -DNDEBUG=1 -DTRIMMED=1
CPPSRCS += reflect.cpp
RTL_FLAGS += -MD
LIBRARY_NAME := toolkit_components_reflect
FORCE_STATIC_LIB := 1
REAL_LIBRARY := toolkit_components_reflect.lib
DEFINES += -DMOZ_HAS_MOZGLUE -DMOZILLA_INTERNAL_API -DIMPL_LIBXUL
