ifndef INCLUDED_AUTOCONF_MK
INCLUDED_AUTOCONF_MK = autoconf-js.mk
include $(DEPTH)/config/emptyvars-js.mk
ACDEFINES = -DBUILD_CTYPES=1 -DCPP_THROW_NEW='throw()' -DCROSS_COMPILE='' -DD_INO=d_ino -DHAVE_64BIT_BUILD=1 -DHAVE_FORCEINLINE=1 -DHAVE_HYPOT=1 -DHAVE_INTTYPES_H=1 -DHAVE_LOCALECONV=1 -DHAVE_MALLOC_H=1 -DHAVE_STDINT_H=1 -DHAVE__GETC_NOLOCK=1 -DHAVE__MSIZE=1 -DJS_CODEGEN_X64=1 -DJS_CPU_X64=1 -DJS_DEFAULT_JITREPORT_GRANULARITY=3 -DJS_HAS_CTYPES=1 -DJS_LTO=1 -DJS_PUNBOX64=1 -DJS_TRACE_LOGGING=1 -DMALLOC_H='<malloc.h>' -DMALLOC_USABLE_SIZE_CONST_PTR=const -DMOZILLA_UAVERSION='"6.2"' -DMOZILLA_VERSION='"6.2.0"' -DMOZILLA_VERSION_U=6.2.0 -DMOZJS_MAJOR_VERSION=6 -DMOZJS_MINOR_VERSION=2 -DMOZ_BUILD_APP=js -DMOZ_DEVTOOLS_SERVER=1 -DMOZ_DLL_SUFFIX='".dll"' -DMOZ_MEMORY=1 -DMOZ_MEMORY_WINDOWS=1 -DMOZ_UPDATE_CHANNEL=default -DNO_NSPR_10_SUPPORT=1 -DRELEASE_OR_BETA=1 -DSTDC_HEADERS=1 -DWIN32=1 -DWIN32_LEAN_AND_MEAN=1 -DWINVER=0x601 -DXP_WIN=1 -DXP_WIN32=1 -DX_DISPLAY_MISSING=1 -DZLIB_IN_MOZGLUE=1 -D_AMD64_=1 -D_CRT_NONSTDC_NO_WARNINGS=1 -D_CRT_SECURE_NO_WARNINGS=1 -D_USE_MATH_DEFINES=1 -D_WIN32_IE=0x0603 -D_WIN32_WINNT=0x601 -D_WINDOWS=1
AR = lib
AR_FLAGS = -NOLOGO -OUT:$@
AS = ml64.exe
AS_DASH_C_FLAG = -c
AUTOCONF = C:/mozilla-build/msys/local/bin/autoconf-2.13
AWK = C:/mozilla-build/msys/bin/gawk.EXE
BIN_SUFFIX = .exe
BUILD_BACKENDS = RecursiveMake FasterMake
BUILD_CTYPES = 1
CC = cl.EXE
CC_TYPE = msvc
CC_VERSION = 19.29.30148
CL_INCLUDES_PREFIX = Note: including file: 
COMPILE_ENVIRONMENT = 1
CPP = cl.EXE -E
CPU_ARCH = x86_64
CROSS_LIB = /usr/x86_64-pc-mingw32
CXX = cl.EXE
CXXCPP = cl.EXE -E
DIST = c:/Work/PaleMoon/White-Star/obj-x86_64-pc-mingw32/dist
DLL_SUFFIX = .dll
DOXYGEN = :
DSO_LDOPTS = -SUBSYSTEM:WINDOWS,6.01 -MACHINE:X64
ENABLE_ION = 1
ENABLE_STRIP = 1
ENABLE_TRACE_LOGGING = 1
EXPAND_LIBS_LIST_STYLE = list
FFI_TARGET = X86_WIN64
FFI_TARGET_DIR = x86
GMAKE = c:/mozilla-build/bin/mozmake.EXE
GRE_MILESTONE = 6.2.0
HAVE_64BIT_BUILD = 1
HAVE_INTTYPES_H = 1
HAVE_YASM = 1
HOST_AR = lib
HOST_AR_FLAGS = -NOLOGO -OUT:$@
HOST_BIN_SUFFIX = .exe
HOST_CC = $(CC)
HOST_CC_TYPE = msvc
HOST_CFLAGS = -TC -nologo -DXP_WIN32 -DXP_WIN -DWIN32 -D_WIN32 -D_CRT_SECURE_NO_WARNINGS -D_AMD64_
HOST_CPU_ARCH = x86_64
HOST_CXX = $(CXX)
HOST_LD = $(LD)
HOST_LDFLAGS =   -MACHINE:X64
HOST_OPTIMIZE_FLAGS = -O2
HOST_OS_ARCH = WINNT
HOST_RANLIB = echo ranlib
IMPORT_LIB_SUFFIX = lib
INCLUDE = C:/PROGRA~2/MICROS~4/2019/COMMUN~1/VC/Tools/MSVC/1429~1.301\include;C:/PROGRA~2/MICROS~4/2019/COMMUN~1/VC/Tools/MSVC/1429~1.301\atlmfc\include;C:\Program Files (x86)\Windows Kits\10\include\10.0.22000.0\shared;C:\Program Files (x86)\Windows Kits\10\include\10.0.22000.0\um;C:\Program Files (x86)\Windows Kits\10\include\10.0.22000.0\winrt;C:\Program Files (x86)\Windows Kits\10\include\10.0.22000.0\ucrt;C:/PROGRA~2/MICROS~4/2019/COMMUN~1/DIA SDK\include;c:/PROGRA~2/MICROS~4/2019/COMMUN~1/VC/Tools/MSVC/1429~1.301\include;c:/PROGRA~2/MICROS~4/2019/COMMUN~1/VC/Tools/MSVC/1429~1.301\atlmfc\include;C:\Program Files (x86)\Windows Kits\10\include\10.0.22000.0\shared;C:\Program Files (x86)\Windows Kits\10\include\10.0.22000.0\um;C:\Program Files (x86)\Windows Kits\10\include\10.0.22000.0\winrt;C:\Program Files (x86)\Windows Kits\10\include\10.0.22000.0\ucrt;c:/PROGRA~2/MICROS~4/2019/COMMUN~1/DIA SDK\include
INCREMENTAL_LINKER = 1
INTEL_ARCHITECTURE = 1
JS_CODEGEN_X64 = 1
JS_CONFIG_LIBS = c:/Work/PaleMoon/White-Star/obj-x86_64-pc-mingw32/dist/lib/nspr4.lib c:/Work/PaleMoon/White-Star/obj-x86_64-pc-mingw32/dist/lib/plc4.lib c:/Work/PaleMoon/White-Star/obj-x86_64-pc-mingw32/dist/lib/plds4.lib   kernel32.lib user32.lib gdi32.lib winmm.lib wsock32.lib advapi32.lib psapi.lib
JS_CONFIG_MOZ_JS_LIBS = ${libdir}/${JS_LIBRARY_NAME}.lib
JS_CONFIG_NAME = js-config
JS_DISABLE_SHELL = 1
JS_HAS_CTYPES = 1
JS_LIBRARY_NAME = mozjs
JS_LTO = 1
JS_SHARED_LIBRARY = 1
JS_SHELL_NAME = js
LD = C:/PROGRA~2/MICROS~4/2019/COMMUN~1/VC/Tools/MSVC/1429~1.301/bin/HostX64/x64/link.exe
LIB = C:/PROGRA~2/MICROS~4/2019/COMMUN~1/VC/Tools/MSVC/1429~1.301\lib\x64;C:/PROGRA~2/MICROS~4/2019/COMMUN~1/VC/Tools/MSVC/1429~1.301\atlmfc\lib\x64;C:\Program Files (x86)\Windows Kits\10\lib\10.0.22000.0\um\x64;C:\Program Files (x86)\Windows Kits\10\lib\10.0.22000.0\ucrt\x64;C:/PROGRA~2/MICROS~4/2019/COMMUN~1/DIA SDK\lib\amd64;c:/PROGRA~2/MICROS~4/2019/COMMUN~1/VC/Tools/MSVC/1429~1.301\lib\x64;c:/PROGRA~2/MICROS~4/2019/COMMUN~1/VC/Tools/MSVC/1429~1.301\atlmfc\lib\x64;C:\Program Files (x86)\Windows Kits\10\lib\10.0.22000.0\um\x64;C:\Program Files (x86)\Windows Kits\10\lib\10.0.22000.0\ucrt\x64;c:/PROGRA~2/MICROS~4/2019/COMMUN~1/DIA SDK\lib\amd64
LIBS_DESC_SUFFIX = desc
LIB_SUFFIX = lib
LINK = C:/PROGRA~2/MICROS~4/2019/COMMUN~1/VC/Tools/MSVC/1429~1.301/bin/HostX64/x64/link.exe
MAKENSISU = c:/mozilla-build/nsis-3.01/makensis-3.01.exe
MKCSHLIB = $(LD) -NOLOGO -DLL -OUT:$@ -PDB:$(LINK_PDBFILE) $(DSO_LDOPTS)
MKSHLIB = $(LD) -NOLOGO -DLL -OUT:$@ -PDB:$(LINK_PDBFILE) $(DSO_LDOPTS)
MOZILLA_SYMBOLVERSION = 6
MOZILLA_VERSION = 6.2.0
MOZJS_MAJOR_VERSION = 6
MOZJS_MINOR_VERSION = 2
MOZJS_PATCH_VERSION = 0
MOZ_APP_NAME = whitestar
MOZ_BUILD_APP = js
MOZ_BUILD_ROOT = c:/Work/PaleMoon/White-Star/obj-x86_64-pc-mingw32/js/src
MOZ_CONFIGURE_OPTIONS = DIST=c:/Work/PaleMoon/White-Star/obj-x86_64-pc-mingw32/dist 'MOZILLABUILD=C:\mozilla-build\' --host=x86_64-pc-mingw32 --target=x86_64-pc-mingw32 CC=cl.EXE CXX=cl.EXE HOST_CC=cl.EXE HOST_CXX=cl.EXE 'LD=C:/PROGRA~2/MICROS~4/2019/COMMUN~1/VC/Tools/MSVC/1429~1.301/bin/HostX64/x64/link.exe' --enable-jemalloc JS_STANDALONE= --disable-js-shell --disable-shared-js --disable-export-js --enable-ctypes MAKE=c:/mozilla-build/bin/mozmake.EXE AUTOCONF=C:/mozilla-build/msys/local/bin/autoconf-2.13 --cache-file=c:/Work/PaleMoon/White-Star/obj-x86_64-pc-mingw32/js/src/config.cache --disable-accessibility --enable-av1 --enable-jxl --disable-eme --disable-gamepad '--enable-optimize=-Od -GTs -GS-' --disable-parental-controls --disable-precompiled-startupcache --enable-strip --disable-updater --disable-webrtc --no-create --prefix=c:/Work/PaleMoon/White-Star/obj-x86_64-pc-mingw32/dist --with-branding=whitestar/branding/whitestar --with-nspr-cflags=-Ic:/Work/PaleMoon/White-Star/obj-x86_64-pc-mingw32/dist/include/nspr '--with-nspr-libs=c:/Work/PaleMoon/White-Star/obj-x86_64-pc-mingw32/dist/lib/nspr4.lib c:/Work/PaleMoon/White-Star/obj-x86_64-pc-mingw32/dist/lib/plc4.lib c:/Work/PaleMoon/White-Star/obj-x86_64-pc-mingw32/dist/lib/plds4.lib '
MOZ_DEBUG_DEFINES = NDEBUG TRIMMED
MOZ_DEBUG_FLAGS = -Zi
MOZ_DEBUG_LDFLAGS = -DEBUG -DEBUGTYPE:CV
MOZ_DEBUG_SYMBOLS = 1
MOZ_DEVTOOLS_SERVER = 1
MOZ_FRAMEPTR_FLAGS = -Oy
MOZ_MEMORY = 1
MOZ_NO_DEBUG_RTL = 1
MOZ_OPTIMIZE = 2
MOZ_OPTIMIZE_FLAGS = -Od -GTs -GS-
MOZ_UPDATE_CHANNEL = default
MSMANIFEST_TOOL = 1
MSVC_CXX_RUNTIME_DLL = msvcp140.dll
MSVC_C_RUNTIME_DLL = vcruntime140.dll
MSVS_VERSION = 2015
MT = c:/PROGRA~2/WI3CF2~1/10/bin/100220~1.0/x64/mt.exe
NONASCII = ¡¡
NSPR_CFLAGS = -Ic:/Work/PaleMoon/White-Star/obj-x86_64-pc-mingw32/dist/include/nspr
OBJ_SUFFIX = obj
OS_ARCH = WINNT
OS_CFLAGS = -TC -nologo -utf-8 -D_HAS_EXCEPTIONS=0 -W3 -Gy -Zc:inline -FS -Gw -wd4244 -wd4267 -we4553
OS_COMPILE_CFLAGS = -FI $(topobjdir)/js/src/js-confdefs.h -DMOZILLA_CLIENT
OS_COMPILE_CXXFLAGS = -FI $(topobjdir)/js/src/js-confdefs.h -DMOZILLA_CLIENT
OS_CXXFLAGS = -TP -nologo -utf-8 -wd4345 -wd4351 -wd4800 -wd4595 -D_CRT_SECURE_NO_WARNINGS -wd5026 -wd5027 -Zc:sizedDealloc- -D_HAS_EXCEPTIONS=0 -W3 -Gy -Zc:inline -FS -Gw -wd4244 -wd4267 -wd4251 -we4553 -GR-
OS_LDFLAGS =  -LARGEADDRESSAWARE -NXCOMPAT -DYNAMICBASE
OS_LIBS =  kernel32.lib user32.lib gdi32.lib winmm.lib wsock32.lib advapi32.lib psapi.lib
OS_TARGET = WINNT
OS_TEST = x86_64
PATH = C:\mozilla-build\msys\local\bin;c:\mozilla-build\bin;c:\mozilla-build\kdiff3;c:\mozilla-build\nsis-3.01;c:\mozilla-build\python;c:\mozilla-build\python\Scripts;c:\mozilla-build\python3;c:\mozilla-build\python3\Scripts;.;C:\mozilla-build\msys\local\bin;C:\mozilla-build\msys\mingw\bin;C:\mozilla-build\msys\bin;c:\WINDOWS\System32;c:\WINDOWS;c:\WINDOWS\System32\Wbem;c:\Program Files\Git\cmd\;c:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.29.30133\bin\HostX64\x64;c:\Program Files (x86)\Windows Kits\10\bin\10.0.22000.0\x64;c:\Program Files (x86)\Windows Kits\10\bin\10.0.22000.0\x86;C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Tools/MSVC/14.29.30133/bin/HostX64/x64;C:/Program Files (x86)/Windows Kits/10/bin/10.0.22000.0/x64;C:/Program Files (x86)/Windows Kits/10/bin/10.0.22000.0/x86
PERL = C:/mozilla-build/msys/bin/perl.EXE
PKG_CONFIG = :
PKG_SKIP_STRIP = 1
PREPROCESS_OPTION = -P -Fi
PROFILE_GEN_CFLAGS = -GL
PROFILE_GEN_LDFLAGS = -LTCG:PGINSTRUMENT
PROFILE_USE_CFLAGS = -GL -wd4624 -wd4952
PROFILE_USE_LDFLAGS = -LTCG:PGUPDATE
PYTHON = c:/Work/PaleMoon/White-Star/obj-x86_64-pc-mingw32/_virtualenv/Scripts/python.exe
RANLIB = echo not_ranlib
RC = rc.exe
RCFLAGS = -nologo
RELEASE_OR_BETA = 1
SHELL = /bin/sh
STRIP = echo not_strip
TARGET_CPU = x86_64
TARGET_OS = mingw32
TARGET_XPCOM_ABI = x86_64-msvc
WIN32_CONSOLE_EXE_LDFLAGS = -SUBSYSTEM:CONSOLE,6.01
WIN32_GUI_EXE_LDFLAGS = -SUBSYSTEM:WINDOWS,6.01
WINDRES = :
WIN_TOP_SRC = c:/Work/PaleMoon/White-Star/platform
XARGS = C:/mozilla-build/msys/bin/xargs.EXE
YASM = c:/mozilla-build/bin/yasm.EXE
YASM_ASFLAGS = -f x64 -rnasm -pnasm
ZLIB_IN_MOZGLUE = 1
_CC = c:/PROGRA~2/MICROS~4/2019/COMMUN~1/VC/Tools/MSVC/1429~1.301/bin/HostX64/x64/cl.EXE
_CXX = c:/PROGRA~2/MICROS~4/2019/COMMUN~1/VC/Tools/MSVC/1429~1.301/bin/HostX64/x64/cl.EXE
_HOST_CC = c:/PROGRA~2/MICROS~4/2019/COMMUN~1/VC/Tools/MSVC/1429~1.301/bin/HostX64/x64/cl.EXE
_HOST_CXX = c:/PROGRA~2/MICROS~4/2019/COMMUN~1/VC/Tools/MSVC/1429~1.301/bin/HostX64/x64/cl.EXE
_MSC_VER = 1929
ac_configure_args =  --cache-file=c:/Work/PaleMoon/White-Star/obj-x86_64-pc-mingw32/js/src/config.cache --disable-accessibility --enable-av1 --enable-jxl --disable-eme --disable-gamepad '--enable-optimize=-Od -GTs -GS-' --disable-parental-controls --disable-precompiled-startupcache --enable-strip --disable-updater --disable-webrtc --prefix=c:/Work/PaleMoon/White-Star/obj-x86_64-pc-mingw32/dist --with-branding=whitestar/branding/whitestar --with-nspr-cflags=-Ic:/Work/PaleMoon/White-Star/obj-x86_64-pc-mingw32/dist/include/nspr '--with-nspr-libs=c:/Work/PaleMoon/White-Star/obj-x86_64-pc-mingw32/dist/lib/nspr4.lib c:/Work/PaleMoon/White-Star/obj-x86_64-pc-mingw32/dist/lib/plc4.lib c:/Work/PaleMoon/White-Star/obj-x86_64-pc-mingw32/dist/lib/plds4.lib ' --host=x86_64-pc-mingw32 --target=x86_64-pc-mingw32 --enable-jemalloc
autoconfmk = autoconf-js.mk
bindir = ${exec_prefix}/bin
build = x86_64-pc-mingw32
build_alias = x86_64-pc-mingw32
build_cpu = x86_64
build_os = mingw32
build_vendor = pc
datadir = ${prefix}/share
exec_prefix = ${prefix}
host = x86_64-pc-mingw32
host_alias = x86_64-pc-mingw32
host_cpu = x86_64
host_os = mingw32
host_vendor = pc
includedir = ${prefix}/include
infodir = ${prefix}/info
libdir = ${exec_prefix}/lib
libexecdir = ${exec_prefix}/libexec
localstatedir = ${prefix}/var
mandir = ${prefix}/man
oldincludedir = /usr/include
prefix = c:/Work/PaleMoon/White-Star/obj-x86_64-pc-mingw32/dist
program_transform_name = s,x,x,
sbindir = ${exec_prefix}/sbin
sharedstatedir = ${prefix}/com
sysconfdir = ${prefix}/etc
target = x86_64-pc-mingw32
target_alias = x86_64-pc-mingw32
target_cpu = x86_64
target_os = mingw32
target_vendor = pc
top_srcdir = c:/Work/PaleMoon/White-Star/platform/js/src/../..
include $(topsrcdir)/config/baseconfig.mk
endif
