# THIS FILE WAS AUTOMATICALLY GENERATED. DO NOT EDIT.

DEFINES += -DNDEBUG=1 -DTRIMMED=1 -DGKMEDIAS_SHARED_LIBRARY
HOST_DEFINES += -DNDEBUG=1 -DTRIMMED=1 -D_UNICODE -DUNICODE
NO_DIST_INSTALL := 1
PYTHON_UNIT_TESTS += tests/test_mozbuild_reading.py
PYTHON_UNIT_TESTS += tests/unit-expandlibs.py
PYTHON_UNIT_TESTS += tests/unit-mozunit.py
PYTHON_UNIT_TESTS += tests/unit-nsinstall.py
PYTHON_UNIT_TESTS += tests/unit-printprereleasesuffix.py
RTL_FLAGS += -MD
VISIBILITY_FLAGS := 
