# THIS FILE WAS AUTOMATICALLY GENERATED. DO NOT EDIT.

DEFINES += -DNDEBUG=1 -DTRIMMED=1
CPPSRCS += ../nsRDFResource.cpp
RTL_FLAGS += -MD
LIBRARY_NAME := rdf_util_internal
FORCE_STATIC_LIB := 1
REAL_LIBRARY := rdf_util_internal.lib
DEFINES += -DMOZ_HAS_MOZGLUE -DMOZILLA_INTERNAL_API -DIMPL_LIBXUL
