# THIS FILE WAS AUTOMATICALLY GENERATED. DO NOT EDIT.

DEFINES += -DNDEBUG=1 -DTRIMMED=1 -D_USE_MATH_DEFINES -Dinline=__inline
LOCAL_INCLUDES += -I$(topsrcdir)/media/libav
CSRCS += cpu.c
AS := c:/mozilla-build/bin/yasm.EXE
ASFLAGS := -f x64 -rnasm -pnasm
AS_DASH_C_FLAG := 
MOZBUILD_ASFLAGS += -D__x86_64__
MOZBUILD_ASFLAGS += -DPIC
MOZBUILD_ASFLAGS += -DWIN64
MOZBUILD_ASFLAGS += -DMSVC
MOZBUILD_ASFLAGS += -Ic:/Work/PaleMoon/White-Star/platform/media/libav
MOZBUILD_ASFLAGS += -Pconfig_win.asm
MOZBUILD_CFLAGS += -wd4090
MOZBUILD_CFLAGS += -wd4018
MOZBUILD_CFLAGS += -wd4305
RTL_FLAGS += -MD
LIBRARY_NAME := media_libav_libavutil_x86
FORCE_STATIC_LIB := 1
REAL_LIBRARY := media_libav_libavutil_x86.lib
DEFINES += -DMOZ_HAS_MOZGLUE
