# THIS FILE WAS AUTOMATICALLY GENERATED. DO NOT EDIT.

DEFINES += -DNDEBUG=1 -DTRIMMED=1
FINAL_TARGET = $(DEPTH)/dist/bin/gmp-fakeopenh264/1.0
CPPSRCS += gmp-fake-openh264.cpp
DISABLE_STL_WRAPPING := 1
RTL_FLAGS += -MT
VISIBILITY_FLAGS := 
LIBRARY_NAME := fakeopenh264
FORCE_SHARED_LIB := 1
IMPORT_LIBRARY := fakeopenh264.lib
SHARED_LIBRARY := fakeopenh264.dll
DSO_SONAME := fakeopenh264.dll
OS_LIBS += ole32.lib
