# THIS FILE WAS AUTOMATICALLY GENERATED. DO NOT EDIT.

DEFINES += -DNDEBUG=1 -DTRIMMED=1 -DIMPL_MFBT
CPPSRCS += StackWalk.cpp
CPPSRCS += TimeStamp.cpp
CPPSRCS += TimeStamp_windows.cpp
RTL_FLAGS += -MD
LIBRARY_NAME := mozglue_misc
FORCE_STATIC_LIB := 1
REAL_LIBRARY := mozglue_misc.lib
OS_LIBS += dbghelp.lib
DEFINES += -DMOZ_HAS_MOZGLUE
