# THIS FILE WAS AUTOMATICALLY GENERATED. DO NOT EDIT.

DEFINES += -DNDEBUG=1 -DTRIMMED=1
DIRS := ../pkix
LOCAL_INCLUDES += -I$(topsrcdir)/security/manager/ssl
LOCAL_INCLUDES += -I$(topsrcdir)/security/pkix/include

# We build files in 'unified' mode by including several files
# together into a single source file.  This cuts down on
# compilation times and debug information size.
UNIFIED_CPPSRCS := Unified_cpp_certverifier0.cpp
CPPSRCS += $(UNIFIED_CPPSRCS)
MOZBUILD_CXXFLAGS += -Wall
MOZBUILD_CXXFLAGS += -wd4355
MOZBUILD_CXXFLAGS += -wd4464
MOZBUILD_CXXFLAGS += -wd4480
MOZBUILD_CXXFLAGS += -wd4481
MOZBUILD_CXXFLAGS += -wd4510
MOZBUILD_CXXFLAGS += -wd4512
MOZBUILD_CXXFLAGS += -wd4514
MOZBUILD_CXXFLAGS += -wd4610
MOZBUILD_CXXFLAGS += -wd4619
MOZBUILD_CXXFLAGS += -wd4623
MOZBUILD_CXXFLAGS += -wd4625
MOZBUILD_CXXFLAGS += -wd4626
MOZBUILD_CXXFLAGS += -wd4628
MOZBUILD_CXXFLAGS += -wd4640
MOZBUILD_CXXFLAGS += -wd4710
MOZBUILD_CXXFLAGS += -wd4711
MOZBUILD_CXXFLAGS += -wd4820
MOZBUILD_CXXFLAGS += -wd4548
MOZBUILD_CXXFLAGS += -wd4668
MOZBUILD_CXXFLAGS += -wd4987
MOZBUILD_CXXFLAGS += -wd4456
MOZBUILD_CXXFLAGS += -wd4458
MOZBUILD_CXXFLAGS += -wd4100
MOZBUILD_CXXFLAGS += -wd4127
MOZBUILD_CXXFLAGS += -wd4946
RTL_FLAGS += -MD
LIBRARY_NAME := security_certverifier
FORCE_STATIC_LIB := 1
REAL_LIBRARY := security_certverifier.lib
DEFINES += -DMOZ_HAS_MOZGLUE -DMOZILLA_INTERNAL_API -DIMPL_LIBXUL
