# THIS FILE WAS AUTOMATICALLY GENERATED. DO NOT EDIT.

DEFINES += -DNDEBUG=1 -DTRIMMED=1
CSRCS += demux.c
ALLOW_COMPILER_WARNINGS := 1
RTL_FLAGS += -MD
LIBRARY_NAME := media_libwebp_demux
FORCE_STATIC_LIB := 1
REAL_LIBRARY := media_libwebp_demux.lib
DEFINES += -DMOZ_HAS_MOZGLUE
