# THIS FILE WAS AUTOMATICALLY GENERATED. DO NOT EDIT.

DEFINES += -DNDEBUG=1 -DTRIMMED=1
CPPSRCS += nsIconChannel.cpp
RTL_FLAGS += -MD
LIBRARY_NAME := image_decoders_icon_win
FORCE_STATIC_LIB := 1
REAL_LIBRARY := image_decoders_icon_win.lib
DEFINES += -DMOZ_HAS_MOZGLUE -DMOZILLA_INTERNAL_API -DIMPL_LIBXUL
