# THIS FILE WAS AUTOMATICALLY GENERATED. DO NOT EDIT.

DEFINES += -DNDEBUG=1 -DTRIMMED=1 -DHAVE_EXPAT_CONFIG_H
CSRCS += xmlparse.c
CSRCS += xmlrole.c
CSRCS += xmltok.c
RTL_FLAGS += -MD
LIBRARY_NAME := parser_expat_lib
FORCE_STATIC_LIB := 1
REAL_LIBRARY := parser_expat_lib.lib
DEFINES += -DMOZ_HAS_MOZGLUE
