# THIS FILE WAS AUTOMATICALLY GENERATED. DO NOT EDIT.

DEFINES += -DNDEBUG -DTRIMMED=1 '-DSHLIB_SUFFIX="dll"' '-DSHLIB_PREFIX=""' '-DSHLIB_VERSION="3"' '-DSOFTOKEN_SHLIB_VERSION="3"' -DRIJNDAEL_INCLUDE_TABLES -DMP_API_COMPATIBLE -DUSE_HW_SHA2 -DKRML_VERIFIED_UINT128 -DNSS_FIPS_DISABLED -DNSS_NO_INIT_SUPPORT -DNSS_X86_OR_X64 -DNSS_X64 -DNSS_USE_64 -DUSE_UTIL_DIRECTLY -DNO_NSPR_10_SUPPORT -DSSL_DISABLE_DEPRECATED_CIPHER_SUITE_NAMES -D_WINDOWS -DWIN95 -D_CRT_SECURE_NO_WARNINGS -D_CRT_NONSTDC_NO_WARNINGS -DNSS_DISABLE_DBM -DNSS_DISABLE_LIBPKIX -DMP_IS_LITTLE_ENDIAN -DNSS_BEVAND_ARCFOUR -DMPI_AMD64 -DMP_ASSEMBLY_MULTIPLY -DNSS_USE_COMBA -DUSE_HW_AES -DINTEL_GCM -DWIN64 -D_AMD64_
LOCAL_INCLUDES += -I$(srcdir)/mpi
LOCAL_INCLUDES += -I$(srcdir)/ecl
LOCAL_INCLUDES += -I$(srcdir)/verified
LOCAL_INCLUDES += -I$(srcdir)/verified/kremlin/include
LOCAL_INCLUDES += -I$(srcdir)/verified/kremlin/kremlib/dist/minimal
LOCAL_INCLUDES += -I$(srcdir)/deprecated
LOCAL_INCLUDES += -I$(topobjdir)/dist/include/nspr
LOCAL_INCLUDES += -I$(topobjdir)/dist/include/private/nss
LOCAL_INCLUDES += -I$(topobjdir)/dist/include/nss
CSRCS += aes-x86.c
CSRCS += gcm-x86.c
ALLOW_COMPILER_WARNINGS := 1
DISABLE_STL_WRAPPING := 1
IS_GYP_DIR := 1
MOZBUILD_CFLAGS += -mpclmul
MOZBUILD_CFLAGS += -maes
NO_PROFILE_GUIDED_OPTIMIZE := 1
RTL_FLAGS += -MD
VISIBILITY_FLAGS := 
LIBRARY_NAME := gcm-aes-x86_c_lib
FORCE_STATIC_LIB := 1
REAL_LIBRARY := gcm-aes-x86_c_lib.lib
