# THIS FILE WAS AUTOMATICALLY GENERATED. DO NOT EDIT.

DEFINES += -DNDEBUG=1 -DTRIMMED=1
CPPSRCS += nsNotifyAddrListener.cpp
RTL_FLAGS += -MD
LIBRARY_NAME := netwerk_system_win32
FORCE_STATIC_LIB := 1
REAL_LIBRARY := netwerk_system_win32.lib
DEFINES += -DMOZ_HAS_MOZGLUE -DMOZILLA_INTERNAL_API -DIMPL_LIBXUL
