# THIS FILE WAS AUTOMATICALLY GENERATED. DO NOT EDIT.

DEFINES += -DNDEBUG=1 -DTRIMMED=1 -DMOZ_EXTENSIONS_DB_SCHEMA=16 -DUXP_APPCOMPAT_GUID=1
DIST_FILES_0 += $(srcdir)/AddonRepository.jsm
DIST_FILES_0 += $(srcdir)/AddonUpdateChecker.jsm
DIST_FILES_0 += $(srcdir)/XPIProvider.jsm
DIST_FILES_0 += $(srcdir)/XPIProviderUtils.js
DIST_FILES_0_PATH := $(DEPTH)/dist/bin/modules/addons
DIST_FILES_0_TARGET := misc
PP_TARGETS += DIST_FILES_0
RTL_FLAGS += -MD
