# THIS FILE WAS AUTOMATICALLY GENERATED. DO NOT EDIT.

DEFINES += -DNDEBUG=1 -DTRIMMED=1 -DGMP_FAKE_SUPPORT_DECRYPT
FINAL_TARGET = $(DEPTH)/dist/bin/gmp-fake/1.0
CPPSRCS += gmp-fake.cpp
CPPSRCS += gmp-test-decryptor.cpp
CPPSRCS += gmp-test-storage.cpp
DISABLE_STL_WRAPPING := 1
RTL_FLAGS += -MT
VISIBILITY_FLAGS := 
LIBRARY_NAME := fake
FORCE_SHARED_LIB := 1
IMPORT_LIBRARY := fake.lib
SHARED_LIBRARY := fake.dll
DSO_SONAME := fake.dll
OS_LIBS += ole32.lib
