# THIS FILE WAS AUTOMATICALLY GENERATED. DO NOT EDIT.

DEFINES += -DNDEBUG=1 -DTRIMMED=1 -Dmozilla_Char16_h
CPPSRCS += fallible.cpp
MOZBUILD_CXXFLAGS += -Zl
RTL_FLAGS += -MD
LIBRARY_NAME := fallible
FORCE_STATIC_LIB := 1
REAL_LIBRARY := fallible.lib
