# THIS FILE WAS AUTOMATICALLY GENERATED. DO NOT EDIT.

DEFINES += -DNDEBUG=1 -DTRIMMED=1
CSRCS += EbmlBufferWriter.c
CSRCS += EbmlWriter.c
CSRCS += WebMElement.c
ALLOW_COMPILER_WARNINGS := 1
RTL_FLAGS += -MD
VISIBILITY_FLAGS := 
LIBRARY_NAME := media_libmkv
FORCE_STATIC_LIB := 1
REAL_LIBRARY := media_libmkv.lib
DEFINES += -DMOZ_HAS_MOZGLUE
