# THIS FILE WAS AUTOMATICALLY GENERATED. DO NOT EDIT.

DEFINES += -DNDEBUG=1 -DTRIMMED=1
LOCAL_INCLUDES += -I$(topsrcdir)/dom/workers
CPPSRCS += AbortController.cpp
CPPSRCS += AbortSignal.cpp
RTL_FLAGS += -MD
LIBRARY_NAME := dom_abort
FORCE_STATIC_LIB := 1
REAL_LIBRARY := dom_abort.lib
DEFINES += -DMOZ_HAS_MOZGLUE -DMOZILLA_INTERNAL_API -DIMPL_LIBXUL
