# THIS FILE WAS AUTOMATICALLY GENERATED. DO NOT EDIT.

DEFINES += -DNDEBUG=1 -DTRIMMED=1
CPPSRCS += nsAppStartupNotifier.cpp
RTL_FLAGS += -MD
LIBRARY_NAME := embedding_components_appstartup
FORCE_STATIC_LIB := 1
REAL_LIBRARY := embedding_components_appstartup.lib
DEFINES += -DMOZ_HAS_MOZGLUE -DMOZILLA_INTERNAL_API -DIMPL_LIBXUL
