# THIS FILE WAS AUTOMATICALLY GENERATED. DO NOT EDIT.

DEFINES += -DNDEBUG=1 -DTRIMMED=1
CPPSRCS += nsJPEGEncoder.cpp
RTL_FLAGS += -MD
LIBRARY_NAME := image_encoders_jpeg
FORCE_STATIC_LIB := 1
REAL_LIBRARY := image_encoders_jpeg.lib
DEFINES += -DMOZ_HAS_MOZGLUE -DMOZILLA_INTERNAL_API -DIMPL_LIBXUL
