# THIS FILE WAS AUTOMATICALLY GENERATED. DO NOT EDIT.

DEFINES += -DNDEBUG=1 -DTRIMMED=1 -DCUBEB_GECKO_BUILD -DUSE_WINMM -DUSE_WASAPI
CSRCS += cubeb.c
CSRCS += cubeb_winmm.c
CPPSRCS += cubeb_panner.cpp
CPPSRCS += cubeb_resampler.cpp
CPPSRCS += cubeb_wasapi.cpp
ALLOW_COMPILER_WARNINGS := 1
MOZBUILD_CXXFLAGS += -wd4005
RTL_FLAGS += -MD
VISIBILITY_FLAGS := 
LIBRARY_NAME := cubeb
FORCE_STATIC_LIB := 1
REAL_LIBRARY := cubeb.lib
DEFINES += -DMOZ_HAS_MOZGLUE
