# THIS FILE WAS AUTOMATICALLY GENERATED. DO NOT EDIT.

DEFINES += -DNDEBUG=1 -DTRIMMED=1 -DMOZ_APP_NAME=whitestar -DAPP_VERSION=32.2.1 -DMOZILLA_VERSION=6.2.0 '-DMOZ_APP_DISPLAYNAME=White Star'
DIST_SUBDIR = browser
FINAL_TARGET = $(if $(XPI_NAME),$(DIST)/xpi-stage/$(XPI_NAME),$(DIST)/bin)$(DIST_SUBDIR:%=/%)
RTL_FLAGS += -MD
