# THIS FILE WAS AUTOMATICALLY GENERATED. DO NOT EDIT.

DEFINES += -DNDEBUG=1 -DTRIMMED=1 -DSQLITE_SECURE_DELETE=1 -DSQLITE_THREADSAFE=1 -DSQLITE_CORE=1 -DSQLITE_ENABLE_FTS3=1 -DSQLITE_ENABLE_UNLOCK_NOTIFY=1 -DSQLITE_ENABLE_DBSTAT_VTAB=1 -DSQLITE_DEFAULT_PAGE_SIZE=32768 -DSQLITE_MAX_DEFAULT_PAGE_SIZE=32768 -DSQLITE_WIN32_GETVERSIONEX=0 -DSQLITE_ALLOW_URI_AUTHORITY=1 -DHAVE_MALLOC_USABLE_SIZE -DSQLITE_WITHOUT_MSIZE -DSQLITE_OMIT_DEPRECATED -DSQLITE_OMIT_BUILTIN_TEST -DSQLITE_OMIT_DECLTYPE -DSQLITE_TEMP_STORE=2
misc:: mozsqlite3.dll.def
GARBAGE += mozsqlite3.dll.def
EXTRA_MDDEPEND_FILES += mozsqlite3.dll.def.pp
mozsqlite3.dll.def: c:/Work/PaleMoon/White-Star/platform/python/mozbuild/mozbuild/action/generate_symbols_file.py $(srcdir)/sqlite.symbols backend.mk
	$(REPORT_BUILD)
	$(call py_action,file_generate,c:/Work/PaleMoon/White-Star/platform/python/mozbuild/mozbuild/action/generate_symbols_file.py generate_symbols_file mozsqlite3.dll.def $(MDDEPDIR)/mozsqlite3.dll.def.pp $(srcdir)/sqlite.symbols -DNDEBUG=1 -DTRIMMED=1 -DSQLITE_SECURE_DELETE=1 -DSQLITE_THREADSAFE=1 -DSQLITE_CORE=1 -DSQLITE_ENABLE_FTS3=1 -DSQLITE_ENABLE_UNLOCK_NOTIFY=1 -DSQLITE_ENABLE_DBSTAT_VTAB=1 -DSQLITE_DEFAULT_PAGE_SIZE=32768 -DSQLITE_MAX_DEFAULT_PAGE_SIZE=32768 -DSQLITE_WIN32_GETVERSIONEX=0 -DSQLITE_ALLOW_URI_AUTHORITY=1 -DHAVE_MALLOC_USABLE_SIZE -DSQLITE_WITHOUT_MSIZE -DSQLITE_OMIT_DEPRECATED -DSQLITE_OMIT_BUILTIN_TEST -DSQLITE_OMIT_DECLTYPE -DSQLITE_TEMP_STORE=2)

CSRCS += sqlite3.c
ALLOW_COMPILER_WARNINGS := 1
MOZBUILD_CFLAGS += -wd4013
RTL_FLAGS += -MD
VISIBILITY_FLAGS := 
LIBRARY_NAME := sqlite
FORCE_SHARED_LIB := 1
IMPORT_LIBRARY := mozsqlite3.lib
SHARED_LIBRARY := mozsqlite3.dll
DSO_SONAME := mozsqlite3.dll
SYMBOLS_FILE := mozsqlite3.dll.def
SHARED_LIBS += $(DEPTH)/mozglue/build/mozglue.lib
STATIC_LIBS += $(DEPTH)/memory/fallible/fallible.lib
DEFINES += -DMOZ_HAS_MOZGLUE
