# THIS FILE WAS AUTOMATICALLY GENERATED. DO NOT EDIT.

DEFINES += -DNDEBUG=1 -DTRIMMED=1 '-DMAR_CHANNEL_ID="unofficial"' '-DMOZ_APP_VERSION="32.2.1"' -DNO_SIGN_VERIFY
HOST_DEFINES += -DNDEBUG=1 -DTRIMMED=1 '-DMAR_CHANNEL_ID="unofficial"' '-DMOZ_APP_VERSION="32.2.1"' -DNO_SIGN_VERIFY
HOST_CSRCS += mar.c
RTL_FLAGS += -MT
HOST_PROGRAM = mar.exe
HOST_LIBS += $(DEPTH)/modules/libmar/src/hostmar.lib
HOST_EXTRA_LIBS += ws2_32.lib
