# THIS FILE WAS AUTOMATICALLY GENERATED. DO NOT EDIT.

DEFINES += -DNDEBUG -DTRIMMED=1 '-DSHLIB_SUFFIX="dll"' '-DSHLIB_PREFIX=""' '-DNSS_SHLIB_VERSION="3"' '-DSOFTOKEN_SHLIB_VERSION="3"' -DNSS_FIPS_DISABLED -DNSS_NO_INIT_SUPPORT -DNSS_X86_OR_X64 -DNSS_X64 -DNSS_USE_64 -DUSE_UTIL_DIRECTLY -DNO_NSPR_10_SUPPORT -DSSL_DISABLE_DEPRECATED_CIPHER_SUITE_NAMES -D_WINDOWS -DWIN95 -D_CRT_SECURE_NO_WARNINGS -D_CRT_NONSTDC_NO_WARNINGS -DNSS_DISABLE_DBM -DNSS_DISABLE_LIBPKIX -DWIN64 -D_AMD64_
LOCAL_INCLUDES += -I$(topobjdir)/dist/include/nspr
LOCAL_INCLUDES += -I$(topobjdir)/dist/include/private/nss
LOCAL_INCLUDES += -I$(topobjdir)/dist/include/nss
CSRCS += dev3hack.c
CSRCS += pk11akey.c
CSRCS += pk11auth.c
CSRCS += pk11cert.c
CSRCS += pk11cxt.c
CSRCS += pk11err.c
CSRCS += pk11hpke.c
CSRCS += pk11kea.c
CSRCS += pk11list.c
CSRCS += pk11load.c
CSRCS += pk11mech.c
CSRCS += pk11merge.c
CSRCS += pk11nobj.c
CSRCS += pk11obj.c
CSRCS += pk11pars.c
CSRCS += pk11pbe.c
CSRCS += pk11pk12.c
CSRCS += pk11pqg.c
CSRCS += pk11sdr.c
CSRCS += pk11skey.c
CSRCS += pk11slot.c
CSRCS += pk11util.c
ALLOW_COMPILER_WARNINGS := 1
DISABLE_STL_WRAPPING := 1
IS_GYP_DIR := 1
NO_PROFILE_GUIDED_OPTIMIZE := 1
RTL_FLAGS += -MD
VISIBILITY_FLAGS := 
LIBRARY_NAME := pk11wrap
FORCE_STATIC_LIB := 1
REAL_LIBRARY := pk11wrap.lib
