# THIS FILE WAS AUTOMATICALLY GENERATED. DO NOT EDIT.

DEFINES += -DNDEBUG=1 -DTRIMMED=1 -D_USE_ANSI_CPP
DIRS := internal
DIST_INSTALL := 1
MOZBUILD_CFLAGS += -Zl
MOZBUILD_CXXFLAGS += -Zl
RTL_FLAGS += -MT
